version: '3.0'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .development.env
    volumes:
    - .:/app
    - /app/node_modules
    ports:
    - 5000:5000
    - 9229:9229
    command: npm run start:dev
    depends_on:
      - postgress
    restart: always

  postgress:
    container_name: postgress
    image: postgres:12
    env_file:
      - .development.env
    environment:
      PG_DATA: /var/lib/posgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/posgresql/data
    restart: always

volumes:
  pgdata:
